# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/abc78/SoC_course/SoC_project_3/SoC_project_3.srcs/sources_1/bd/SoC/ip/SoC_axi_gpio_1_1/SoC_axi_gpio_1_1.xci
# IP: The module: 'SoC_axi_gpio_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/abc78/SoC_course/SoC_project_3/SoC_project_3.srcs/sources_1/bd/SoC/ip/SoC_axi_gpio_1_1/SoC_axi_gpio_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SoC_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/abc78/SoC_course/SoC_project_3/SoC_project_3.srcs/sources_1/bd/SoC/ip/SoC_axi_gpio_1_1/SoC_axi_gpio_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SoC_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/abc78/SoC_course/SoC_project_3/SoC_project_3.srcs/sources_1/bd/SoC/ip/SoC_axi_gpio_1_1/SoC_axi_gpio_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'SoC_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/abc78/SoC_course/SoC_project_3/SoC_project_3.srcs/sources_1/bd/SoC/ip/SoC_axi_gpio_1_1/SoC_axi_gpio_1_1.xci
# IP: The module: 'SoC_axi_gpio_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/abc78/SoC_course/SoC_project_3/SoC_project_3.srcs/sources_1/bd/SoC/ip/SoC_axi_gpio_1_1/SoC_axi_gpio_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SoC_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/abc78/SoC_course/SoC_project_3/SoC_project_3.srcs/sources_1/bd/SoC/ip/SoC_axi_gpio_1_1/SoC_axi_gpio_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SoC_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/abc78/SoC_course/SoC_project_3/SoC_project_3.srcs/sources_1/bd/SoC/ip/SoC_axi_gpio_1_1/SoC_axi_gpio_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'SoC_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
