# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/SoC/SoC.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SoC || ORIG_REF_NAME==SoC} -quiet] -quiet

# IP: bd/SoC/ip/SoC_processing_system7_0_1/SoC_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SoC_processing_system7_0_1 || ORIG_REF_NAME==SoC_processing_system7_0_1} -quiet] -quiet

# IP: bd/SoC/ip/SoC_axi_gpio_0_1/SoC_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SoC_axi_gpio_0_1 || ORIG_REF_NAME==SoC_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SoC/ip/SoC_xbar_1/SoC_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SoC_xbar_1 || ORIG_REF_NAME==SoC_xbar_1} -quiet] -quiet

# IP: bd/SoC/ip/SoC_ps7_0_axi_periph_1/SoC_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SoC_ps7_0_axi_periph_1 || ORIG_REF_NAME==SoC_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/SoC/ip/SoC_rst_ps7_0_50M_1/SoC_rst_ps7_0_50M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SoC_rst_ps7_0_50M_1 || ORIG_REF_NAME==SoC_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/SoC/ip/SoC_axi_gpio_1_1/SoC_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SoC_axi_gpio_1_1 || ORIG_REF_NAME==SoC_axi_gpio_1_1} -quiet] -quiet

# IP: bd/SoC/ip/SoC_auto_pc_0/SoC_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SoC_auto_pc_0 || ORIG_REF_NAME==SoC_auto_pc_0} -quiet] -quiet

# XDC: bd/SoC/SoC_ooc.xdc
